// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: test.sql

package repository

import (
	"context"
)

const getTestById = `-- name: GetTestById :one
select id, test_name
from test_table
where id = $1
limit 1
`

func (q *Queries) GetTestById(ctx context.Context, id int32) (TestTable, error) {
	row := q.db.QueryRowContext(ctx, getTestById, id)
	var i TestTable
	err := row.Scan(&i.ID, &i.TestName)
	return i, err
}
